# Generated by Django 6.1.1 on 2026-10-08 09:50

import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferenceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('task_assignment_alerts', models.BooleanField(default=True)),
                ('task_overdue_alerts', models.BooleanField(default=True)),
                ('leave_status_alerts', models.BooleanField(default=True)),
                ('attendance_reminder_alerts', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification preference setting',
                'verbose_name_plural': 'notification preference settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EMWTS Workplace Solutions', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_assets/', validators=[organization.models.validate_org_logo])),
                ('timezone', models.CharField(default='UTC', max_length=100, validators=[organization.models.validate_timezone_name])),
                ('contact_email', models.EmailField(blank=True, default='admin@emwts.local', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=35)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='https://emwts.local')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization setting',
                'verbose_name_plural': 'organization settings',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administration audit log',
                'verbose_name_plural': 'administration audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_optional', models.BooleanField(default=False)),
                ('is_recurring_annually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='unique_holiday_date_name')],
            },
        ),
    ]
