# Generated by Django 6.1.1 on 2026-10-08 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_DEADLINE_APPROACHING', 'Task Deadline Approaching'), ('TASK_OVERDUE', 'Task Overdue'), ('LEAVE_SUBMITTED', 'Leave Request Submitted'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('ATTENDANCE_REMINDER', 'Attendance Reminder'), ('ANNOUNCEMENT', 'Administrative Announcement')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('target_model', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('deduplication_key', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
