# Generated by Django 6.1.1 on 2026-10-01 18:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Corporate Schedule', max_length=100)),
                ('work_start_time', models.TimeField(default='09:00:00')),
                ('work_end_time', models.TimeField(default='18:00:00')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('half_day_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4)),
                ('full_day_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('HOLIDAY', 'Holiday'), ('ON_LEAVE', 'On Leave')], db_index=True, default='PRESENT', max_length=20)),
                ('work_duration_minutes', models.PositiveIntegerField(default=0)),
                ('work_duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['-date', '-check_in'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_check_in', models.DateTimeField(blank=True, null=True)),
                ('original_check_out', models.DateTimeField(blank=True, null=True)),
                ('original_status', models.CharField(max_length=20)),
                ('new_check_in', models.DateTimeField(blank=True, null=True)),
                ('new_check_out', models.DateTimeField(blank=True, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'attendance correction',
                'verbose_name_plural': 'attendance corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_daily_attendance'),
        ),
    ]
